const words = [
    "VERSION",
    "GENE",
    "CHEST",
    "COMMUNITY",
    "POLITICS",
    "CHILDHOOD",
    "SIGNATURE",
    "GROCERY",
    "EXTENT",
    "IDEA",
    "SOUP",
    "MEMBER",
    "BATH",
    "USER",
    "DIRT",
    "SOCIETY",
    "PRESIDENT",
    "WEALTH",
    "GROWTH",
    "HIGHWAY",
    "VILLAGE",
    "FAILURE",
    "TRAINER",
    "DEPARTURE",
    "ADDITION",
    "ROLE",
    "QUALITY",
    "OFFICE",
    "WINNER",
    "METHOD",
    "STRANGER",
    "EMPLOYEE",
    "LEADER",
    "CABINET",
    "PAINTING",
    "PRIORITY",
    "GATE",
    "COMPLAINT",
    "AREA",
    "NIGHT",
    "TENSION",
    "PERSON",
    "ECONOMICS",
    "APARTMENT",
    "ROAD",
    "HOUSING",
    "EMPHASIS",
    "WEDDING",
    "DINNER",
    "CAMERA"
];

export const getAlphabets = () => "ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("");

export const getRandomWord = () =>
    words[Math.floor(Math.random() * words.length)];
